import { createBrowserClient } from '@supabase/ssr'

// Browser client — the only Supabase client 'use client' components may import.
// Deliberately does NOT use getEnv(): that validates the full server schema
// (including secrets) against process.env, and Next.js only inlines
// process.env.NEXT_PUBLIC_X when it appears as a literal member access —
// a generic object pass-through leaves every key undefined in the browser
// bundle. Read the two NEXT_PUBLIC_ vars directly instead (NextMove's pattern).
//
// No typed Database generic yet: src/types/database.ts is generated by
// `supabase gen types typescript` (task T015), which requires a running local
// Supabase instance and hasn't been run in this environment yet. Once it lands,
// wire `createBrowserClient<Database>(...)` here.
export function createClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY

  if (!supabaseUrl || !supabaseKey) {
    throw new Error('Missing Supabase environment variables')
  }

  return createBrowserClient(supabaseUrl, supabaseKey)
}
