import { createBrowserClient } from '@supabase/ssr'

import { getEnv } from '@/lib/env'

// Browser client — the only Supabase client 'use client' components may import.
// No typed Database generic yet: src/types/database.ts is generated by
// `supabase gen types typescript` (task T015), which requires a running local
// Supabase instance and hasn't been run in this environment yet. Once it lands,
// wire `createBrowserClient<Database>(...)` here.
export function createClient() {
  const env = getEnv()
  return createBrowserClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY)
}
