import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'

import { getEnv } from '@/lib/env'

// Server client, bound to the current request's cookies. Server Components and
// Route Handlers use this to run queries as the signed-in user under RLS.
//
// Always call `.auth.getUser()` on the returned client when you need to trust
// the caller's identity — never `.auth.getSession()`. getSession() trusts
// whatever is in the cookie without revalidating the JWT against Supabase;
// getUser() round-trips to Supabase and is the only call that actually proves
// the session is still valid (docs/design/002-schema.md §F).
//
// No typed Database generic yet — src/types/database.ts is generated by task
// T015, not yet run in this environment (requires a running local Supabase
// instance). Wire `createServerClient<Database>(...)` once it lands.
export async function createClient() {
  const env = getEnv()
  const cookieStore = await cookies()

  return createServerClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY, {
    cookies: {
      getAll() {
        return cookieStore.getAll()
      },
      setAll(cookiesToSet) {
        try {
          cookiesToSet.forEach(({ name, value, options }) => {
            cookieStore.set(name, value, options)
          })
        } catch {
          // Server Components can't set cookies — this is expected there.
          // Session refresh happens in src/proxy.ts, which runs in a context
          // that CAN write the response's Set-Cookie header.
        }
      },
    },
  })
}
