import 'server-only'

import { createClient as createSupabaseClient } from '@supabase/supabase-js'

import { getEnv } from '@/lib/env'

// Service-role client — bypasses RLS entirely. Only for trusted server-side
// paths that must act across tenants (webhook handlers, admin scripts, cron
// jobs) — never for a request acting on behalf of a specific user; use
// src/lib/supabase/server.ts for that so RLS stays the authority.
//
// Two layers keep this out of the browser:
//   1. The `server-only` import throws at build time if this module is ever
//      pulled into a client bundle.
//   2. eslint.config.mjs bans importing this module from any .tsx file (where
//      'use client' components live in this codebase).
// This runtime check is a third, belt-and-suspenders layer for any non-.tsx
// path (e.g. a misconfigured route handler) that somehow still runs in a
// browser-like environment.
if (typeof window !== 'undefined') {
  throw new Error(
    'src/lib/supabase/service.ts must never be imported into browser-executed code — it holds the service-role key, which bypasses Row Level Security entirely.',
  )
}

// No typed Database generic yet — src/types/database.ts is generated by task
// T015, not yet run in this environment (requires a running local Supabase
// instance). Wire `createSupabaseClient<Database>(...)` once it lands.
export function createServiceClient() {
  const env = getEnv()
  return createSupabaseClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SECRET_KEY, {
    auth: {
      persistSession: false,
    },
  })
}
